apiVersion: v1
kind: Secret
metadata:
  name: upload-service-secret
type: Opaque
stringData:
  RABBITMQ_USER: "default_user_IaiG3HmNdPVqcnwOye9"
  RABBITMQ_PASSWORD: "FoBzBncVMpHli7pzQXL8q849Z30MyCc_"

  MINIO_ACCESS_KEY: "minioadmin"
  MINIO_SECRET_KEY: "minioadmin"