apiVersion: v1
kind: Service
metadata:
  name: upload-service
  labels:
    app: upload-service
spec:
  type: ClusterIP 
  selector:
    app: upload-service
  ports:
  - name: web
    port: 8080
    targetPort: 8080
  - name: monitor
    port: 8081
    targetPort: 8081