env: dev

http:
  port: 8080

jwt:
  public_key: public_key.pem

minio:
  endpoint: localhost:9000
  bucket_name: videos
  access_key: BPYUnB5lsb2sR8OKZYcL
  secret_key: iKScGSBikEX4H4EBfX7PacXTaXfUA7hOmenpVm0S
  use_secure: false