env: prod

http:
  port: 8080

rabbitmq:
  user: guest
  password: guest
  host: rabbitmq
  port: 5672
  queue_name: video_processing

minio:
  endpoint: minio-server:9000
  bucket_name: videos
  access_key: BPYUnB5lsb2sR8OKZYcL
  secret_key: iKScGSBikEX4H4EBfX7PacXTaXfUA7hOmenpVm0S
  use_secure: false