name: Deploy to Yandex Cloud Kubernetes

on:
  push:
    branches: [main, dev]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up project
        uses: VideoHosting-Platform/actions/.github/actions/setup-and-deploy@main
        with:
          registry: 'docker.io'
          image_name: '${{ secrets.DOCKERHUB_USERNAME }}/upload-service'
          folder_id: '${{ secrets.FOLDER_ID }}'
          cluster_id: '${{ secrets.CLUSTER_ID }}'
          dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
          yc_service_account_key: ${{ secrets.YC_SERVICE_ACCOUNT_KEY }}
      - name: Login to GitHub Container Registry
        run: |
          echo "${{ secrets.GHUB_TOKEN }}" | helm registry login ghcr.io \
            --username ${{ github.actor }} \
            --password-stdin

      - name: Deploy
        run: |
          kubectl get pods
          helm upgrade video-hosting \
            oci://ghcr.io/redblood-pixel/charts/video-hosting-stack \
            --reuse-values \
            --set 'upload-service.image.tag=${{ github.sha }}'

