name: Deploy to Yandex Cloud Kubernetes

on:
  push:
    branches: [ dev ]

env:
  FOLDER_ID: b1gq90lppq2qo7ofbuhb
  CLUSTER_ID: mk8s-cluster

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup YC CLI and kubectl
      uses: andreyvlassenko/setup-yc-k8s@v1
      with:
        yc-sa-json-key: ${{ secrets.YC_SERVICE_ACCOUNT_KEY }}
        folder-id: ${{ env.FOLDER_ID }}
        cluster-id: ${{ env.CLUSTER_ID }}

    - name: Deploy test application
      run: |
        # Применяем тестовый манифест
        kubectl apply -f - <<EOF
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: nginx-test-deployment
        spec:
          replicas: 2
          selector:
            matchLabels:
              app: nginx-test
          template:
            metadata:
              labels:
                app: nginx-test
            spec:
              containers:
              - name: nginx
                image: nginx:1.25
                ports:
                - containerPort: 80
        ---
        apiVersion: v1
        kind: Service
        metadata:
          name: nginx-test-service
        spec:
          type: ClusterIP
          selector:
            app: nginx-test
          ports:
            - port: 80
              targetPort: 80
        EOF

        # Проверяем состояние деплоя
        kubectl get pods -w
        kubectl get svc